POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhcmhhbnQiLCJpZCI6IjVlYTMyMDhhOTYzNDg3NGFmNzA3MWQyMSIsImlhdCI6MTU4Nzc1MTM3MH0.QGGXbidYHVBKgPOcLgN6XiXW0mBus0sltDIAwPyRRoE

{
    "title": "Blog 9",
    "author": "Farhan Tahie",
    "url": "localhost:3002/fake",
    "likes": 0
}